sudo: required

dist: focal

services:
  - docker

before_install:
  - docker build -t sbl_docs .
  - mkdir -p build publish
  - chmod 777 build publish
  - touch publish/.nojekyll
  - export GIT_SAFE_DIR_CMD="git config --global --add safe.directory /docs" # Fix error caused by CVE-2022-24765 Git update

script:
  - docker run --rm -v ${PWD}:/docs -w /docs sbl_docs /bin/bash -c "${GIT_SAFE_DIR_CMD} && make publish BUILDDIR=/docs/build PUBLISHDIR=/docs/publish"

before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger
  - gem install faraday-net_http -v 3.3.0


deploy:
  provider: pages
  local-dir: publish
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: ssbyna/bynadoc
  target-branch: master

